/*
** EPITECH PROJECT, 2021
** B_CPP_300_BER_3_1_CPPD16_karl_erik_stoerzel
** File description:
** KoalaAction.hpp
*/

#ifndef B_CPP_300_BER_3_1_CPPD16_KARL_ERIK_STOERZEL_KOALAACTION_HPP
#define B_CPP_300_BER_3_1_CPPD16_KARL_ERIK_STOERZEL_KOALAACTION_HPP
class KoalaAction
{

};
#endif //B_CPP_300_BER_3_1_CPPD16_KARL_ERIK_STOERZEL_KOALAACTION_HPP
